"""Mechanical periphery drift checks for landed correspondence rows."""

from __future__ import annotations

from dataclasses import dataclass
import importlib
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass(frozen=True)
class PromisedTestSurface:
    test_file: str
    test_names: tuple[str, ...]


@dataclass(frozen=True)
class PeripheryCorrespondenceExpectation:
    row_label: str
    home_path: str
    module_path: str | None
    symbol_name: str | None
    promised_surfaces: tuple[PromisedTestSurface, ...]


EXPECTATIONS = (
    PeripheryCorrespondenceExpectation(
        row_label="EventTraceArtifact",
        home_path="cortex/eval/artifacts.py",
        module_path="cortex.eval.artifacts",
        symbol_name="EventTraceArtifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_certification_artifacts.py",
                test_names=("test_current_pair_fragment_carries_event_trace_and_verdict_summary",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="CurrentPairFragment",
        home_path="cortex/eval/artifacts.py",
        module_path="cortex.eval.artifacts",
        symbol_name="CurrentPairFragment",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_certification_artifacts.py",
                test_names=("test_current_pair_fragment_carries_event_trace_and_verdict_summary",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="BlockerFragment",
        home_path="cortex/eval/artifacts.py",
        module_path="cortex.eval.artifacts",
        symbol_name="BlockerFragment",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_certification_artifacts.py",
                test_names=("test_blocker_fragment_preserves_reason_and_contradictions",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="EvaluationHarnessResult",
        home_path="cortex/eval/harness.py",
        module_path="cortex.eval.harness",
        symbol_name="EvaluationHarnessResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_eval_harness.py",
                test_names=(
                    "test_harness_result_carries_current_pair_without_losing_refs",
                    "test_harness_result_carries_blocker_without_smoothing_blocker_truth",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="build_evaluation_harness_result",
        home_path="cortex/eval/harness.py",
        module_path="cortex.eval.harness",
        symbol_name="build_evaluation_harness_result",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_eval_harness.py",
                test_names=(
                    "test_harness_requires_exactly_one_outcome_fragment",
                    "test_harness_result_needs_no_publication_packet_surface",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="EvaluationPacket",
        home_path="cortex/eval/packets.py",
        module_path="cortex.eval.packets",
        symbol_name="EvaluationPacket",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_eval_packets.py",
                test_names=(
                    "test_packet_built_from_current_pair_preserves_truth_and_withheld_fields",
                    "test_packet_built_from_blocker_preserves_truth_and_withheld_fields",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="build_evaluation_packet",
        home_path="cortex/eval/packets.py",
        module_path="cortex.eval.packets",
        symbol_name="build_evaluation_packet",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_eval_packets.py",
                test_names=(
                    "test_packet_build_preserves_contradictions_and_degradations",
                    "test_packet_build_requires_no_measured_example_or_runtime_wiring",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="REFERENCE_HOST_SURFACE",
        home_path="cortex/drivers/reference_host.py",
        module_path="cortex.drivers.reference_host",
        symbol_name="REFERENCE_HOST_SURFACE",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_host.py",
                test_names=("test_bound_event_carrier_contains_surface_observation_and_normalized_payload",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="BoundReferenceHostEvent",
        home_path="cortex/drivers/reference_host.py",
        module_path="cortex.drivers.reference_host",
        symbol_name="BoundReferenceHostEvent",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_host.py",
                test_names=("test_bound_event_carrier_contains_surface_observation_and_normalized_payload",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="bind_reference_event_envelope",
        home_path="cortex/drivers/reference_host.py",
        module_path="cortex.drivers.reference_host",
        symbol_name="bind_reference_event_envelope",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_host.py",
                test_names=("test_alias_event_name_binds_to_canonical_core_name_and_preserves_raw_name",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="observe_reference_host_event",
        home_path="cortex/drivers/reference_host.py",
        module_path="cortex.drivers.reference_host",
        symbol_name="observe_reference_host_event",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_host.py",
                test_names=(
                    "test_proposal_like_raw_host_event_binds_cleanly_and_is_dispatch_ready",
                    "test_ordinary_context_event_binds_without_commitment_time_work",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceHostCommitmentResult",
        home_path="cortex/drivers/reference_host_commitment.py",
        module_path="cortex.drivers.reference_host_commitment",
        symbol_name="ReferenceHostCommitmentResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_host_commitment.py",
                test_names=(
                    "test_full_commitment_reference_host_event_with_concrete_provenance_yields_certified",
                    "test_proposal_like_event_stays_out_of_certification_and_returns_no_verdict",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="bind_reference_host_candidate",
        home_path="cortex/drivers/reference_host_commitment.py",
        module_path="cortex.drivers.reference_host_commitment",
        symbol_name="bind_reference_host_candidate",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_host_commitment.py",
                test_names=(
                    "test_candidate_binding_prefers_direct_payload_id_over_extracted_structured_id",
                    "test_candidate_binding_falls_back_to_extracted_structured_id",
                    "test_candidate_binding_synthesizes_deterministic_local_id_when_none_is_present",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="evaluate_reference_host_commitment",
        home_path="cortex/drivers/reference_host_commitment.py",
        module_path="cortex.drivers.reference_host_commitment",
        symbol_name="evaluate_reference_host_commitment",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_host_commitment.py",
                test_names=(
                    "test_full_commitment_reference_host_event_with_concrete_provenance_yields_certified",
                    "test_blocked_boundary_yields_blocked_even_when_provenance_exists",
                    "test_missing_evidence_yields_uncertified",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceHostNeutralResult",
        home_path="cortex/drivers/reference_host_neutral.py",
        module_path="cortex.drivers.reference_host_neutral",
        symbol_name="ReferenceHostNeutralResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_reference_host_neutral.py",
                test_names=(
                    "test_ordinary_context_event_yields_explicit_neutral_continuation_result",
                    "test_vertical_slice_stays_observe_bind_driven_and_preserves_raw_host_metadata",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="NeutralContinuationDecision",
        home_path="cortex/drivers/reference_host_neutral.py",
        module_path="cortex.drivers.reference_host_neutral",
        symbol_name="NeutralContinuationDecision",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_reference_host_neutral.py",
                test_names=(
                    "test_ordinary_context_event_yields_explicit_neutral_continuation_result",
                    "test_proposal_like_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_event_is_rejected_from_neutral_only_path",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="NeutralContinuationCode",
        home_path="cortex/drivers/reference_host_neutral.py",
        module_path="cortex.drivers.reference_host_neutral",
        symbol_name="NeutralContinuationCode",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_reference_host_neutral.py",
                test_names=(
                    "test_ordinary_context_event_yields_explicit_neutral_continuation_result",
                    "test_proposal_like_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_event_is_rejected_from_neutral_only_path",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="evaluate_reference_host_neutral",
        home_path="cortex/drivers/reference_host_neutral.py",
        module_path="cortex.drivers.reference_host_neutral",
        symbol_name="evaluate_reference_host_neutral",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_reference_host_neutral.py",
                test_names=(
                    "test_ordinary_context_event_yields_explicit_neutral_continuation_result",
                    "test_proposal_like_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_event_is_rejected_from_neutral_only_path",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="GEMINI_HOST_SURFACE",
        home_path="cortex/drivers/gemini_host.py",
        module_path="cortex.drivers.gemini_host",
        symbol_name="GEMINI_HOST_SURFACE",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host.py",
                test_names=("test_bound_gemini_event_contains_surface_observation_and_remains_dispatch_cheap",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="BoundGeminiHostEvent",
        home_path="cortex/drivers/gemini_host.py",
        module_path="cortex.drivers.gemini_host",
        symbol_name="BoundGeminiHostEvent",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host.py",
                test_names=("test_bound_gemini_event_contains_surface_observation_and_remains_dispatch_cheap",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="bind_gemini_event_envelope",
        home_path="cortex/drivers/gemini_host.py",
        module_path="cortex.drivers.gemini_host",
        symbol_name="bind_gemini_event_envelope",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host.py",
                test_names=("test_documented_gemini_event_binds_to_canonical_core_name_and_preserves_raw_name",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="observe_gemini_host_event",
        home_path="cortex/drivers/gemini_host.py",
        module_path="cortex.drivers.gemini_host",
        symbol_name="observe_gemini_host_event",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host.py",
                test_names=(
                    "test_documented_gemini_event_binds_to_canonical_core_name_and_preserves_raw_name",
                    "test_normalized_gemini_payload_preserves_stable_generic_fields_when_present",
                    "test_bound_gemini_event_contains_surface_observation_and_remains_dispatch_cheap",
                    "test_gemini_surface_gap_emits_explicit_warning_instead_of_fabricated_parity",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="GeminiHostCommitmentResult",
        home_path="cortex/drivers/gemini_host_commitment.py",
        module_path="cortex.drivers.gemini_host_commitment",
        symbol_name="GeminiHostCommitmentResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host_commitment.py",
                test_names=(
                    "test_full_commitment_gemini_event_with_concrete_provenance_yields_certified",
                    "test_candidate_bearing_gemini_event_stays_out_of_certification_and_returns_no_verdict",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="bind_gemini_host_candidate",
        home_path="cortex/drivers/gemini_host_commitment.py",
        module_path="cortex.drivers.gemini_host_commitment",
        symbol_name="bind_gemini_host_candidate",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host_commitment.py",
                test_names=("test_candidate_binding_prefers_direct_payload_id_then_extracted_then_synthesized",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="evaluate_gemini_host_commitment",
        home_path="cortex/drivers/gemini_host_commitment.py",
        module_path="cortex.drivers.gemini_host_commitment",
        symbol_name="evaluate_gemini_host_commitment",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host_commitment.py",
                test_names=(
                    "test_full_commitment_gemini_event_with_concrete_provenance_yields_certified",
                    "test_blocked_boundary_yields_blocked_even_when_provenance_exists",
                    "test_missing_evidence_yields_uncertified",
                    "test_candidate_bearing_gemini_event_stays_out_of_certification_and_returns_no_verdict",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="GeminiHostNeutralResult",
        home_path="cortex/drivers/gemini_host_neutral.py",
        module_path="cortex.drivers.gemini_host_neutral",
        symbol_name="GeminiHostNeutralResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host_neutral.py",
                test_names=(
                    "test_ordinary_gemini_streaming_event_yields_explicit_neutral_continuation_result",
                    "test_slice_stays_observe_bind_driven_and_preserves_raw_gemini_metadata_and_warnings",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="GeminiNeutralContinuationDecision",
        home_path="cortex/drivers/gemini_host_neutral.py",
        module_path="cortex.drivers.gemini_host_neutral",
        symbol_name="GeminiNeutralContinuationDecision",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host_neutral.py",
                test_names=(
                    "test_ordinary_gemini_streaming_event_yields_explicit_neutral_continuation_result",
                    "test_candidate_bearing_gemini_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_gemini_event_is_rejected_from_neutral_only_path",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="GeminiNeutralContinuationCode",
        home_path="cortex/drivers/gemini_host_neutral.py",
        module_path="cortex.drivers.gemini_host_neutral",
        symbol_name="GeminiNeutralContinuationCode",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host_neutral.py",
                test_names=(
                    "test_ordinary_gemini_streaming_event_yields_explicit_neutral_continuation_result",
                    "test_candidate_bearing_gemini_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_gemini_event_is_rejected_from_neutral_only_path",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="evaluate_gemini_host_neutral",
        home_path="cortex/drivers/gemini_host_neutral.py",
        module_path="cortex.drivers.gemini_host_neutral",
        symbol_name="evaluate_gemini_host_neutral",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_gemini_host_neutral.py",
                test_names=(
                    "test_ordinary_gemini_streaming_event_yields_explicit_neutral_continuation_result",
                    "test_candidate_bearing_gemini_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_gemini_event_is_rejected_from_neutral_only_path",
                    "test_slice_stays_observe_bind_driven_and_preserves_raw_gemini_metadata_and_warnings",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OPENAI_HOST_SURFACE",
        home_path="cortex/drivers/openai_host.py",
        module_path="cortex.drivers.openai_host",
        symbol_name="OPENAI_HOST_SURFACE",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host.py",
                test_names=("test_bound_openai_event_contains_surface_observation_and_remains_dispatch_cheap",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="BoundOpenAIHostEvent",
        home_path="cortex/drivers/openai_host.py",
        module_path="cortex.drivers.openai_host",
        symbol_name="BoundOpenAIHostEvent",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host.py",
                test_names=("test_bound_openai_event_contains_surface_observation_and_remains_dispatch_cheap",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="bind_openai_event_envelope",
        home_path="cortex/drivers/openai_host.py",
        module_path="cortex.drivers.openai_host",
        symbol_name="bind_openai_event_envelope",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host.py",
                test_names=("test_documented_openai_event_binds_to_canonical_core_name_and_preserves_raw_name",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="observe_openai_host_event",
        home_path="cortex/drivers/openai_host.py",
        module_path="cortex.drivers.openai_host",
        symbol_name="observe_openai_host_event",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host.py",
                test_names=(
                    "test_documented_openai_event_binds_to_canonical_core_name_and_preserves_raw_name",
                    "test_normalized_openai_payload_preserves_stable_generic_fields_when_present",
                    "test_bound_openai_event_contains_surface_observation_and_remains_dispatch_cheap",
                    "test_openai_surface_gap_emits_explicit_warning_instead_of_fabricated_parity",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OpenAIHostCommitmentResult",
        home_path="cortex/drivers/openai_host_commitment.py",
        module_path="cortex.drivers.openai_host_commitment",
        symbol_name="OpenAIHostCommitmentResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host_commitment.py",
                test_names=(
                    "test_full_commitment_openai_event_with_concrete_provenance_yields_certified",
                    "test_candidate_bearing_openai_event_stays_out_of_certification_and_returns_no_verdict",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="bind_openai_host_candidate",
        home_path="cortex/drivers/openai_host_commitment.py",
        module_path="cortex.drivers.openai_host_commitment",
        symbol_name="bind_openai_host_candidate",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host_commitment.py",
                test_names=("test_candidate_binding_prefers_direct_payload_id_then_extracted_then_synthesized",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="evaluate_openai_host_commitment",
        home_path="cortex/drivers/openai_host_commitment.py",
        module_path="cortex.drivers.openai_host_commitment",
        symbol_name="evaluate_openai_host_commitment",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host_commitment.py",
                test_names=(
                    "test_full_commitment_openai_event_with_concrete_provenance_yields_certified",
                    "test_blocked_boundary_yields_blocked_even_when_provenance_exists",
                    "test_missing_evidence_yields_uncertified",
                    "test_candidate_bearing_openai_event_stays_out_of_certification_and_returns_no_verdict",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OpenAIHostNeutralResult",
        home_path="cortex/drivers/openai_host_neutral.py",
        module_path="cortex.drivers.openai_host_neutral",
        symbol_name="OpenAIHostNeutralResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host_neutral.py",
                test_names=(
                    "test_ordinary_openai_streaming_event_yields_explicit_neutral_continuation_result",
                    "test_slice_stays_observe_bind_driven_and_preserves_raw_openai_metadata_and_warnings",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OpenAINeutralContinuationDecision",
        home_path="cortex/drivers/openai_host_neutral.py",
        module_path="cortex.drivers.openai_host_neutral",
        symbol_name="OpenAINeutralContinuationDecision",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host_neutral.py",
                test_names=(
                    "test_ordinary_openai_streaming_event_yields_explicit_neutral_continuation_result",
                    "test_candidate_bearing_openai_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_openai_event_is_rejected_from_neutral_only_path",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OpenAINeutralContinuationCode",
        home_path="cortex/drivers/openai_host_neutral.py",
        module_path="cortex.drivers.openai_host_neutral",
        symbol_name="OpenAINeutralContinuationCode",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host_neutral.py",
                test_names=(
                    "test_ordinary_openai_streaming_event_yields_explicit_neutral_continuation_result",
                    "test_candidate_bearing_openai_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_openai_event_is_rejected_from_neutral_only_path",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="evaluate_openai_host_neutral",
        home_path="cortex/drivers/openai_host_neutral.py",
        module_path="cortex.drivers.openai_host_neutral",
        symbol_name="evaluate_openai_host_neutral",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_host_neutral.py",
                test_names=(
                    "test_ordinary_openai_streaming_event_yields_explicit_neutral_continuation_result",
                    "test_candidate_bearing_openai_event_is_rejected_from_neutral_only_path",
                    "test_full_commitment_openai_event_is_rejected_from_neutral_only_path",
                    "test_slice_stays_observe_bind_driven_and_preserves_raw_openai_metadata_and_warnings",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceRealizationFeedback",
        home_path="cortex/sre/feedback.py",
        module_path="cortex.sre.feedback",
        symbol_name="ReferenceRealizationFeedback",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_realization_feedback.py",
                test_names=(
                    "test_reference_realization_feedback_preserves_last_step_shell_outcome",
                    "test_reference_realization_feedback_rejects_noncanonical_commitment_kind",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceRealizationFeedbackWindow",
        home_path="cortex/sre/feedback.py",
        module_path="cortex.sre.feedback",
        symbol_name="ReferenceRealizationFeedbackWindow",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_feedback_window.py",
                test_names=(
                    "test_reference_realization_feedback_window_starts_empty",
                    "test_reference_realization_feedback_window_keeps_only_three_most_recent_entries",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceFeedbackWindowSummary",
        home_path="cortex/sre/feedback.py",
        module_path="cortex.sre.feedback",
        symbol_name="ReferenceFeedbackWindowSummary",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_feedback_window.py",
                test_names=(
                    "test_summarize_reference_feedback_window_reports_zero_pressure_for_clean_window",
                    "test_summarize_reference_feedback_window_reports_repeated_rejection_floor_and_sustained_disruption",
                    "test_summarize_reference_feedback_window_reports_mixed_rejection_and_override_bonus",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="summarize_reference_feedback_window",
        home_path="cortex/sre/feedback.py",
        module_path="cortex.sre.feedback",
        symbol_name="summarize_reference_feedback_window",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_feedback_window.py",
                test_names=(
                    "test_summarize_reference_feedback_window_reports_single_rejection_floor",
                    "test_summarize_reference_feedback_window_reports_repeated_override_floor",
                    "test_summarize_reference_feedback_window_reports_mixed_rejection_and_override_bonus",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceControlLedger",
        home_path="cortex/runtime/reference.py",
        module_path="cortex.runtime.reference",
        symbol_name="ReferenceControlLedger",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_step.py",
                test_names=(
                    "test_reference_runtime_step_result_surfaces_cheap_reference_event_without_commitment_kind",
                    "test_reference_runtime_step_result_certifies_full_commitment_when_runtime_payload_supplies_artifact_ref",
                    "test_reference_runtime_step_orders_admissible_families_by_soft_control_enum",
                    "test_reference_runtime_step_orders_dominant_uncertainty_sources_by_level_then_tag",
                    "test_reference_runtime_step_prioritizes_enforcement_as_primary_reason_over_session_warning",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceRuntimeSession",
        home_path="cortex/runtime/reference.py",
        module_path="cortex.runtime.reference",
        symbol_name="ReferenceRuntimeSession",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_step.py",
                test_names=(
                    "test_reference_runtime_session_tracks_minimum_live_state",
                    "test_reference_runtime_step_propagates_session_rejection_feedback_into_next_event_pressure",
                    "test_reference_runtime_step_appends_feedback_window_and_truncates_oldest_entry",
                ),
            ),
            PromisedTestSurface(
                test_file="tests/integration/test_reference_runtime_continuity.py",
                test_names=(
                    "test_reference_runtime_cli_preserves_open_suspend_resume_merge_continuity_in_one_session",
                    "test_reference_runtime_cli_rejects_illegal_continuity_transitions_without_mutating_session_truth",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceRuntimeStepResult",
        home_path="cortex/runtime/reference.py",
        module_path="cortex.runtime.reference",
        symbol_name="ReferenceRuntimeStepResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_step.py",
                test_names=(
                    "test_reference_runtime_step_result_surfaces_cheap_reference_event_without_commitment_kind",
                    "test_reference_runtime_step_result_certifies_full_commitment_when_runtime_payload_supplies_artifact_ref",
                    "test_reference_runtime_step_reports_prior_window_summary_for_single_rejection_sequence",
                    "test_reference_runtime_step_enforces_latched_brake_to_check_when_evidence_dominates",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="ReferenceRuntimeSessionArtifact",
        home_path="cortex/runtime/reference_session_io.py",
        module_path="cortex.runtime.reference_session_io",
        symbol_name="ReferenceRuntimeSessionArtifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_session_io.py",
                test_names=(
                    "test_reference_runtime_session_artifact_roundtrips_empty_session",
                    "test_reference_runtime_session_artifact_roundtrips_populated_continuity_truth",
                    "test_reference_runtime_session_artifact_roundtrips_bounded_residue_without_full_histories",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="build_reference_runtime_session_artifact",
        home_path="cortex/runtime/reference_session_io.py",
        module_path="cortex.runtime.reference_session_io",
        symbol_name="build_reference_runtime_session_artifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_session_io.py",
                test_names=(
                    "test_reference_runtime_session_artifact_roundtrips_bounded_residue_without_full_histories",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="parse_reference_runtime_session_artifact",
        home_path="cortex/runtime/reference_session_io.py",
        module_path="cortex.runtime.reference_session_io",
        symbol_name="parse_reference_runtime_session_artifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_session_io.py",
                test_names=(
                    "test_reference_runtime_session_artifact_rejects_wrong_kind_and_version",
                    "test_reference_runtime_session_artifact_rejects_unknown_keys_everywhere",
                    "test_reference_runtime_session_artifact_rejects_invalid_enums",
                    "test_reference_runtime_session_artifact_rejects_mismatched_last_feedback_and_window",
                    "test_reference_runtime_session_artifact_one_sided_last_feedback_normalizes_through_session_constructor",
                    "test_reference_runtime_session_artifact_one_sided_window_only_normalizes_through_session_constructor",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="read_reference_runtime_session_artifact",
        home_path="cortex/runtime/reference_session_io.py",
        module_path="cortex.runtime.reference_session_io",
        symbol_name="read_reference_runtime_session_artifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_session_io.py",
                test_names=(
                    "test_reference_runtime_session_artifact_read_write_roundtrip_uses_json_file",
                ),
            ),
            PromisedTestSurface(
                test_file="tests/integration/test_reference_runtime_cli.py",
                test_names=(
                    "test_reference_runtime_cli_bad_load_artifact_exits_non_zero_and_emits_no_stdout",
                    "test_reference_runtime_cli_zero_event_load_save_roundtrip_works",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="write_reference_runtime_session_artifact",
        home_path="cortex/runtime/reference_session_io.py",
        module_path="cortex.runtime.reference_session_io",
        symbol_name="write_reference_runtime_session_artifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_session_io.py",
                test_names=(
                    "test_reference_runtime_session_artifact_read_write_roundtrip_uses_json_file",
                ),
            ),
            PromisedTestSurface(
                test_file="tests/integration/test_reference_runtime_cli.py",
                test_names=(
                    "test_reference_runtime_cli_save_session_does_not_change_jsonl_output",
                    "test_reference_runtime_cli_same_path_load_and_save_replaces_artifact",
                    "test_reference_runtime_cli_save_failure_emits_no_stdout",
                    "test_reference_runtime_cli_zero_event_load_save_roundtrip_works",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OpenAIRuntimeSession",
        home_path="cortex/runtime/openai.py",
        module_path="cortex.runtime.openai",
        symbol_name="OpenAIRuntimeSession",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_runtime_session_io.py",
                test_names=("test_openai_runtime_session_artifact_roundtrips_bounded_residue",),
            ),
            PromisedTestSurface(
                test_file="tests/integration/test_openai_runtime_continuity.py",
                test_names=("test_openai_runtime_split_session_is_o1_equivalent_to_uninterrupted_run",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OpenAIControlLedger",
        home_path="cortex/runtime/openai.py",
        module_path="cortex.runtime.openai",
        symbol_name="OpenAIControlLedger",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_openai_runtime_cli.py",
                test_names=("test_openai_runtime_cli_reads_documented_raw_events_and_preserves_host_name",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OpenAIRuntimeStepResult",
        home_path="cortex/runtime/openai.py",
        module_path="cortex.runtime.openai",
        symbol_name="OpenAIRuntimeStepResult",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_openai_runtime_cli.py",
                test_names=("test_openai_runtime_cli_reads_documented_raw_events_and_preserves_host_name",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="run_openai_runtime_step",
        home_path="cortex/runtime/openai.py",
        module_path="cortex.runtime.openai",
        symbol_name="run_openai_runtime_step",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_openai_runtime_cli.py",
                test_names=(
                    "test_openai_runtime_cli_reads_documented_raw_events_and_preserves_host_name",
                    "test_openai_runtime_cli_undocumented_raw_host_event_warns_without_fabricating_parity",
                ),
            ),
            PromisedTestSurface(
                test_file="tests/unit/test_openai_runtime_step.py",
                test_names=(
                    "test_openai_runtime_step_rejects_canonical_cortex_event_name_before_runtime_processing",
                ),
            ),
            PromisedTestSurface(
                test_file="tests/integration/test_openai_runtime_continuity.py",
                test_names=("test_openai_runtime_host_warning_and_certified_commitment_can_coexist_across_restart",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="OpenAIRuntimeSessionArtifact",
        home_path="cortex/runtime/openai_session_io.py",
        module_path="cortex.runtime.openai_session_io",
        symbol_name="OpenAIRuntimeSessionArtifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_runtime_session_io.py",
                test_names=("test_openai_runtime_session_artifact_roundtrips_bounded_residue",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="build_openai_runtime_session_artifact",
        home_path="cortex/runtime/openai_session_io.py",
        module_path="cortex.runtime.openai_session_io",
        symbol_name="build_openai_runtime_session_artifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_runtime_session_io.py",
                test_names=("test_openai_runtime_session_artifact_roundtrips_bounded_residue",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="parse_openai_runtime_session_artifact",
        home_path="cortex/runtime/openai_session_io.py",
        module_path="cortex.runtime.openai_session_io",
        symbol_name="parse_openai_runtime_session_artifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_runtime_session_io.py",
                test_names=(
                    "test_openai_runtime_session_artifact_rejects_unknown_keys_and_invalid_enums",
                    "test_openai_runtime_session_artifact_one_sided_last_feedback_normalizes_through_session_constructor",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="read_openai_runtime_session_artifact",
        home_path="cortex/runtime/openai_session_io.py",
        module_path="cortex.runtime.openai_session_io",
        symbol_name="read_openai_runtime_session_artifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_runtime_session_io.py",
                test_names=("test_openai_runtime_session_artifact_same_path_overwrite_safety",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="write_openai_runtime_session_artifact",
        home_path="cortex/runtime/openai_session_io.py",
        module_path="cortex.runtime.openai_session_io",
        symbol_name="write_openai_runtime_session_artifact",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_openai_runtime_session_io.py",
                test_names=("test_openai_runtime_session_artifact_same_path_overwrite_safety",),
            ),
            PromisedTestSurface(
                test_file="tests/integration/test_openai_runtime_cli.py",
                test_names=("test_openai_runtime_cli_explicit_load_save_works",),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="build_openai_cli_record",
        home_path="cortex/runtime/openai_cli.py",
        module_path="cortex.runtime.openai_cli",
        symbol_name="build_openai_cli_record",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_openai_runtime_cli.py",
                test_names=(
                    "test_openai_runtime_cli_reads_documented_raw_events_and_preserves_host_name",
                    "test_openai_runtime_cli_undocumented_raw_host_event_warns_without_fabricating_parity",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="run_reference_runtime_step",
        home_path="cortex/runtime/reference.py",
        module_path="cortex.runtime.reference",
        symbol_name="run_reference_runtime_step",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_reference_runtime_step.py",
                test_names=(
                    "test_reference_runtime_step_result_surfaces_cheap_reference_event_without_commitment_kind",
                    "test_reference_runtime_step_result_keeps_candidate_bearing_event_candidate_only",
                    "test_reference_runtime_step_result_certifies_full_commitment_when_runtime_payload_supplies_artifact_ref",
                    "test_reference_runtime_step_rejects_malformed_open_without_mutating_existing_anchor",
                    "test_reference_runtime_step_rejects_mismatched_session_id_without_reassigning_shell",
                    "test_reference_runtime_step_propagates_session_rejection_feedback_into_next_event_pressure",
                    "test_reference_runtime_step_propagates_prior_enforcement_override_into_next_event_pressure",
                    "test_reference_runtime_step_does_not_raise_feedback_pressure_after_clean_success",
                    "test_reference_runtime_step_appends_feedback_window_and_truncates_oldest_entry",
                    "test_reference_runtime_step_orders_admissible_families_by_soft_control_enum",
                    "test_reference_runtime_step_orders_dominant_uncertainty_sources_by_level_then_tag",
                    "test_reference_runtime_step_prioritizes_enforcement_as_primary_reason_over_session_warning",
                    "test_reference_runtime_step_enforces_latched_brake_to_check_when_evidence_dominates",
                    "test_reference_runtime_step_enforces_latched_brake_to_neutral_without_evidence_or_environment",
                ),
            ),
            PromisedTestSurface(
                test_file="tests/integration/test_reference_runtime_continuity.py",
                test_names=(
                    "test_reference_runtime_cli_preserves_open_suspend_resume_merge_continuity_in_one_session",
                    "test_reference_runtime_cli_rejects_illegal_continuity_transitions_without_mutating_session_truth",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="build_reference_cli_record",
        home_path="cortex/runtime/reference_cli.py",
        module_path="cortex.runtime.reference_cli",
        symbol_name="build_reference_cli_record",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_reference_runtime_cli.py",
                test_names=(
                    "test_reference_runtime_cli_reads_event_file_and_emits_one_record_per_event",
                    "test_reference_runtime_cli_reads_stdin_and_preserves_locked_output_contract",
                    "test_reference_runtime_cli_in_process_surfaces_selected_vs_realized_divergence",
                    "test_reference_runtime_cli_emits_feedback_window_summary_for_real_session_mismatch_sequences",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="augment_snapshot",
        home_path="cortex/aux/augmentation.py",
        module_path="cortex.aux.augmentation",
        symbol_name="augment_snapshot",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_aux_scaffolds.py",
                test_names=(
                    "test_augment_snapshot_requires_explicit_support_snapshot_and_preserves_core_view",
                    "test_augment_snapshot_appends_auxiliary_support_without_mutating_core_snapshot_semantics",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="AuxBurdenReport",
        home_path="cortex/aux/cost.py",
        module_path="cortex.aux.cost",
        symbol_name="AuxBurdenReport",
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/unit/test_aux_scaffolds.py",
                test_names=(
                    "test_aux_burden_report_enforces_non_negative_values",
                    "test_aux_scaffold_types_remain_domain_general_and_removable",
                ),
            ),
        ),
    ),
    PeripheryCorrespondenceExpectation(
        row_label="aux_claim_conservative_enforcement_test",
        home_path="tests/integration/test_aux_claim_conservative.py",
        module_path=None,
        symbol_name=None,
        promised_surfaces=(
            PromisedTestSurface(
                test_file="tests/integration/test_aux_claim_conservative.py",
                test_names=(
                    "test_certified_outcome_is_unchanged_by_aux_augmentation_and_burden_presence",
                    "test_blocked_outcome_is_unchanged_by_aux_augmentation_and_burden_presence",
                    "test_uncertified_outcome_is_unchanged_by_aux_augmentation_and_burden_presence",
                    "test_aux_objects_remain_support_side_and_do_not_enter_commitment_apis",
                ),
            ),
        ),
    ),
)


@pytest.mark.parametrize("expectation", EXPECTATIONS, ids=lambda item: item.row_label)
def test_periphery_correspondence_registry_resolves_code_home_and_test_surface(
    expectation: PeripheryCorrespondenceExpectation,
) -> None:
    home_path = REPO_ROOT / expectation.home_path
    assert home_path.is_file(), (
        f"{expectation.row_label}: expected code home {expectation.home_path}"
    )

    if expectation.module_path and expectation.symbol_name:
        module = importlib.import_module(expectation.module_path)
        assert hasattr(module, expectation.symbol_name), (
            f"{expectation.row_label}: missing symbol {expectation.symbol_name} "
            f"in module {expectation.module_path}"
        )

    for promised_surface in expectation.promised_surfaces:
        test_file = REPO_ROOT / promised_surface.test_file
        assert test_file.is_file(), (
            f"{expectation.row_label}: expected promised test file {promised_surface.test_file}"
        )

        test_text = test_file.read_text(encoding="utf-8")
        for test_name in promised_surface.test_names:
            assert f"def {test_name}(" in test_text, (
                f"{expectation.row_label}: missing promised test function {test_name} "
                f"in {promised_surface.test_file}"
            )


def test_v1_comparison_rows_match_landed_runtime_and_sre_truth() -> None:
    correspondence_text = (
        REPO_ROOT / "docs" / "CORTEX_V2_MATH_TO_CODE_CORRESPONDENCE.md"
    ).read_text(encoding="utf-8")

    assert "| Deficit state `D_t` | `stop_signals.py` objective_gap_signature | `u_t(c)` uncertainty classes (SRE-owned) | `UncertaintyEstimate` |" in correspondence_text
    assert "| Transition / residue `R_t` | objective_gap_state, loop_detected | `X_t^{ref}` executive state (SRE-owned) | `ReferenceExecutiveState` |" in correspondence_text
    assert "| Action / control `A_t` | stop_stage, recommend_revert, feedback_mode | `U_t^{sre}` soft-control output | soft-control selection |" in correspondence_text
